# Тема 10. Декораторы и исключения.
### Отчет по Теме #10 выполнил:
- Ланцов Матвей
- ПИЭ-21-2

| Задание | Лаб. раб. | Сам. раб. |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |

Работу проверили:
- к.э.н., доцент Панов М.А.

## Самостоятельная работа 
## Задание №1
Вовочка решил заняться спортивным программированием на python, но
для этого он должен знать за какое время выполняется его программа.
Он решил, что для этого ему идеально подойдет декоратор для
функции, который будет выяснять за какое время выполняется та или
иная функция. Помогите Вовочке в его начинаниях и напишите такой
декоратор.
Подсказка: необходимо использовать модуль time
Декоратор необходимо использовать для этой функции

#### Выполнение:
```python
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"Время выполнения функции {func.__name__}: {execution_time} секунд")
        return result
    return wrapper

@timing_decorator
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()

```
#### Результат:

![image](https://github.com/qq072/MatveyLantsov/assets/103333884/c67f79ab-fea0-4448-959b-67219de31226)


### Вывод:  декоратор timing_decorator принимает функцию func и возвращает новую функцию wrapper, которая измеряет время выполнения func. Декоратор затем применяется к функции fibonacci с помощью символа @. Когда fibonacci() вызывается, декоратор автоматически измеряет время выполнения этой функции и выводит результат.

## Задание №2
Посмотрев на Вовочку, вы также загорелись идеей спортивного
программирования, начав тренировки вы узнали, что для решения
некоторых задач необходимо считывать данные из файлов. Но через
некоторое время вы столкнулись с проблемой что файлы бывают
пустыми, и вы не получаете вводные данные для решения задачи.
После этого вы решили не просто считывать данные из файла, а всю
конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то
информация. Напишите код программы. Если файл пустой, то, нужно
вызвать исключение (“бросить исключение”) и вывести в консоль
“файл пустой”, а если он не пустой, то вывести информацию из файла.

#### Выполнение:
```python
def read_file(file_path):
    try:
        with open(file_path, 'r') as file:
            content = file.read()
            if not content:
                raise Exception("Файл пустой")
            else:
                print("Информация из файла:")
                print(content)
    except FileNotFoundError:
        print(f"Файл '{file_path}' не найден")
    except Exception as e:
        print(f"Исключение: {e}")

if __name__ == '__main__':
    # Пример использования для пустого файла
    print("Для пустого файла:")
    read_file('empty_file.txt')

    print("\n" + "="*30 + "\n")

    # Пример использования для файла с информацией
    print("Для файла с информацией:")
    read_file('non_empty_file.txt')


```
#### Результат:
![image](https://github.com/qq072/MatveyLantsov/assets/103333884/6eab619c-bab8-4ba7-bc3a-1a057906eb8f)


### Вывод: Этот код определяет функцию read_file, которая сначала пытается открыть файл, читает его содержимое и проверяет, не является ли файл пустым. Если файл пустой, генерируется исключение с сообщением "Файл пустой". Если файл не пустой, выводится содержимое файла. Если файл не найден, обрабатывается исключение FileNotFoundError.


## Задание №3
Напишите функцию, которая будет складывать 2 и введенное
пользователем число, но если пользователь введет строку или другой
неподходящий тип данных, то в консоль выведется ошибка
“Неподходящий тип данных. Ожидалось число.”. Реализовать
функционал программы необходимо через try/except и подобрать
правильный тип исключения. Создавать собственное исключение
нельзя. Проведите несколько тестов, в которых исключение вызывается
и нет. Результатом выполнения задачи будет листинг кода и
получившийся вывод в консоль

#### Выполнение:
```python
def add_two_and_number():
    try:
        user_input = input("Введите число: ")
        result = 2 + float(user_input)
        print(f"Результат сложения: {result}")
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")

if __name__ == '__main__':
    # Тест 1: ввод корректного числа
    add_two_and_number(10)

    # Тест 2: ввод строки вместо числа
    add_two_and_number("fjskf")

    # Тест 3: ввод другого неподходящего типа данных
    add_two_and_number("-2")

```
#### Результат:
![image](https://github.com/qq072/MatveyLantsov/assets/103333884/a64eb395-1328-4381-b08c-1926346e69d5)


### Вывод:используется исключение ValueError, которое возникает, если происходит ошибка преобразования строки в число с помощью float(). Если пользователь вводит корректное число, программа выполняется успешно. Если пользователь вводит строку или другой неподходящий тип данных, перехватывается исключение, и выводится соответствующее сообщение об ошибке.


## Задание №4
Создайте собственный декоратор, который будет использоваться для
двух любых вами придуманных функций. Декораторы, которые
использовались ранее в работе нельзя воссоздавать. Результатом
выполнения задачи будет: класс декоратора, две как-то связанными с
ним функциями, скриншот консоли с выполненной программой и
подробные комментарии, которые будут описывать работу вашего
кода.

#### Выполнение:
```python
  import time

class TimingDecorator:
    def __init__(self, func):
        self.func = func

    def __call__(self, *args, **kwargs):
        start_time = time.time()
        result = self.func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"Время выполнения функции {self.func.__name__}: {execution_time} секунд")
        return result

@TimingDecorator
def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

@TimingDecorator
def generate_squares(n):
    return [i ** 2 for i in range(1, n + 1)]

if __name__ == '__main__':
    print(factorial(5))

    print(generate_squares(5))

```
#### Результат:
![image](https://github.com/qq072/MatveyLantsov/assets/103333884/d7c4c53e-2906-41cf-b65e-32bc440b1b8f)


### Вывод: В этом коде создается класс TimingDecorator, который служит в качестве декоратора. Он принимает функцию в конструкторе и переопределяет метод __call__, чтобы измерять время выполнения переданной функции.
Далее, используем этот декоратор для двух функций: factorial (вычисление факториала) и generate_squares (генерация списка квадратов чисел). Результат выполнения каждой функции выводится в консоль, включая время выполнения, измеренное с использованием нашего декоратора.


## Задание №5
Создайте собственный декоратор, который будет использоваться для
двух любых вами придуманных функций. Декораторы, которые
использовались ранее в работе нельзя воссоздавать. Результатом
выполнения задачи будет: класс декоратора, две как-то связанными с
ним функциями, скриншот консоли с выполненной программой и
подробные комментарии, которые будут описывать работу вашего
кода.

#### Выполнение:
```python
class CustomError(Exception):
    def __init__(self, message="Произошла ошибка"):
        self.message = message
        super().__init__(self.message)

def process_user_data(name, age):
    try:
        if not name or not age:
            raise CustomError("Имя и возраст должны быть заполнены")

        if not isinstance(age, int) or age < 0:
            raise CustomError("Некорректный формат возраста")

        print(f"Данные пользователя: Имя - {name}, Возраст - {age} лет")
    except CustomError as e:
        print(f"Ошибка при обработке данных пользователя: {e}")

def read_file_content(file_path):
    try:
        with open(file_path, 'r') as file:
            content = file.read()
            if not content:
                raise CustomError("Файл пустой")
            else:
                print(f"Содержимое файла: {content}")
    except CustomError as e:
        print(f"Ошибка при чтении файла: {e}")

if __name__ == '__main__':
    # Тест 1: Правильные данные пользователя
    process_user_data("John Doe", 30)

    # Тест 2: Некорректный возраст (вызовет исключение)
    process_user_data("Alice", -25)

    # Тест 3: Пустое имя пользователя (вызовет исключение)
    process_user_data("", 22)

    # Тест 4: Чтение содержимого файла
    read_file_content("example_file.txt")

    # Тест 5: Чтение из пустого файла (вызовет исключение)
    read_file_content("empty_file.txt")

```
#### Результат:

![image](https://github.com/qq072/MatveyLantsov/assets/103333884/5513bff3-fd2d-4325-b047-7ba58efcaf28)

### Вывод: В этом коде используется исключение CustomError для обработки ошибок в двух сценариях: при обработке данных пользователя и при чтении файла. Если возникает ошибка, программа выводит соответствующее сообщение.

## Общий вывод: В Python декораторы и исключения являются важными элементами языка, предоставляющими эффективные и гибкие механизмы для организации кода и обработки ошибок.
